name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.JS
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - name: Install Root Dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint Check
        run: pnpm lint

      - name: Format Check
        run: pnpm format

      - name: Build Check
        run: pnpm build
